
seata:
  application-id: seata-tm
  tx-service-group: default_tx_group
  #  use-jdk-proxy: true
  #  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: seata
      data-id: seataServer.properties
      namespace: a167d1a5-9427-4f78-a488-caab48aed290
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: seata
      cluster: default
      namespace: a167d1a5-9427-4f78-a488-caab48aed290
server:
  port: 1124
spring:
  application:
    name: seata-rms
    # ????????
  datasource:
    url: jdbc:mysql://47.101.167.248:3306/ds0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 # ??????????????????0?
      min-idle: 5 # ??????????????????????????????????????????????????0?
      max-active: 20 # ???????????????????????????????????????????????????????8?
      max-wait: 60000 # ??????????????????????????????????????????????-1????????
      time-between-eviction-runs-millis: 60000 # ???????????????????????????60000???1????
      min-evictable-idle-time-millis: 300000 # ???????????????????????????????????????300000???5????
      validation-query: SELECT 1998 # ???????????SQL?????Druid?????????????????????"SELECT 1"?
      test-while-idle: true # ??????????????????????true?????????????????????????????????????true?
      test-on-borrow: false # ??????????????????????????true???????????????????????????false?
      test-on-return: false # ??????????????????????????true???????????????????????false?
      pool-prepared-statements: true # ????????????????????????????????SQL?????????true?
      max-pool-prepared-statement-per-connection-size: 20 #?????????????????????20?
  config:
    import: "nacos:seata-tms"
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: seata
        namespace: a167d1a5-9427-4f78-a488-caab48aed290


dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-port: 9811
  protocol:
    name: tri
    port: 50051
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    parameters:
      namespace: 90099803-50cd-469c-a064-dab6010ad773      #shxlchange
      group: dubbo #??????????????





#mybatis:
#  mapper-locations: classpath*:/mapper/**/*.xml