
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000

server:
  port: 6377
spring:
  config:
    import: classpath:base.yml

# https://redisson.org/docs/integration-with-spring/
#  redis:
#    redisson:
#      file: classpath:redisson.yml
