
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000

# spring.application.name=spring-boot-jetcache-mvc
server:
  port: 6377
spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          #password: 'NFTurbo666'  #??????????????
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://127.0.0.1:6379"   #shxlchange
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
logging:
  level:
    org:
      springframework:
        cache: DEBUG