spring:
  config:
    import: classpath:base.yml
  elasticsearch:
    uris:
      - http://192.168.40.95:9200
      - http://192.168.40.95:9201
      - http://192.168.40.95:9202
    connection-timeout: 5s
    socket-timeout: 3s
logging:
  level:
    org.springframework.data.elasticsearch: DEBUG