#seata:
#  application-id: ${spring.application.name}
#  tx-service-group: default_tx_group
#  #  use-jdk-proxy: true
#  #  enable-auto-data-source-proxy: false
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: seata
#      data-id: seataServer.properties
#      namespace: a167d1a5-9427-4f78-a488-caab48aed290
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: seata
#      cluster: default
#      namespace: a167d1a5-9427-4f78-a488-caab48aed290
