spring:
  datasource:
    url: jdbc:mysql://47.101.167.248:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8099
logging:
  level:
    org.mybatis: debug