server:
  port: 1125
spring:
  application:
    name: seata-rms2
      # 可选：指定配置组
  datasource:
    url: jdbc:mysql://47.101.167.248:3306/seata_rm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 # 连接池初始化时创建的连接数。默认值为0。
      min-idle: 5 # 连接池中保持的最小空闲连接数量。当连接池中的连接数量小于这个值时，连接池会尝试创建新的连接。默认值为0。
      max-active: 20 # 连接池中允许的最大连接数。如果所有连接都被使用并且没有空闲连接，新的连接请求将被阻塞，直到有连接可用。默认值为8。
      max-wait: 60000 # 获取连接时的最大等待时间，单位为毫秒。如果在指定的时间内无法获取到连接，将抛出异常。默认值为-1，表示无限等待。
      time-between-eviction-runs-millis: 60000 # 连接池每次检测空闲连接的间隔时间，单位为毫秒。默认值为60000毫秒（1分钟）。
      min-evictable-idle-time-millis: 300000 # 连接在连接池中的最小空闲时间，超过这个时间的连接将被回收，单位为毫秒。默认值为300000毫秒（5分钟）。
      validation-query: SELECT 1998 # 用于验证连接是否有效的SQL查询语句。Druid会定期执行此查询来检测连接的可用性。默认为"SELECT 1"。
      test-while-idle: true # 是否在连接空闲时检测连接的有效性。如果设置为true，则连接池会定期检测空闲连接，如果连接失效，将被标记为不可用并移除。默认为true。
      test-on-borrow: false # 是否在从连接池借用连接时检测连接的有效性。如果设置为true，每次从连接池借用连接时都会执行连接有效性检测。默认为false。
      test-on-return: false # 是否在归还连接到连接池时检测连接的有效性。如果设置为true，连接在归还到连接池时会进行有效性检测。默认为false。
      pool-prepared-statements: true # 是否开启预处理语句池。预处理语句池可以提高性能，特别是在执行相同SQL语句多次时。默认为true。
      max-pool-prepared-statement-per-connection-size: 20 #每个连接上允许的最大预处理语句数。默认值为20。
  config:
    import: nacos:seata-tms,classpath:base.yml
  cloud:
    nacos:
      config:
        server-addr: ${base.host}:8848
        group: seata
        namespace: a167d1a5-9427-4f78-a488-caab48aed290

seata:
  application-id: seata-tm
  tx-service-group: default_tx_group
  #  use-jdk-proxy: true
  #  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: ${base.host}:8848
      group: seata
      data-id: seataServer.properties
      namespace: a167d1a5-9427-4f78-a488-caab48aed290
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${base.host}:8848
      group: seata
      cluster: default
      namespace: a167d1a5-9427-4f78-a488-caab48aed290
  data-source-proxy-mode: AT
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-port: 9812
    #https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/#dubboprotocol
  protocol:
    port: 50050
    name: dubbo
  registry:
    address: nacos://${base.host}:8848?username=nacos&password=nacos
    parameters:
      namespace: 90099803-50cd-469c-a064-dab6010ad773      #shxlchange
      group: dubbo
  consumer:
    timeout: 6000000
  config-center:
    timeout: 6000000
logging:
  level:
    com.baomidou.mybatisplus: info
    org.apache.ibatis: info
